import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/providers/auth";
import Header from "@/components/ui/Header";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono"; // モノスペースフォントも必要な場合

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}
      >
        <AuthProvider>
          <Header />
          <main className="min-h-screen">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
